services:
  product-service-db:
    image: postgres:latest
    restart: always
    ports:
      - "${PRODUCT_DB_PORT}:5432"
    volumes:
      - /postgres/product-service/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${PRODUCT_DB_NAME}