services:
  product-service-db:
    image: postgres:16
    restart: always
    ports:
      - "1115:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: product-service-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d product-service-db" ]
      interval: 20s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  product-service:
    build: .
    restart: always
    depends_on:
      product-service-db:
        condition: service_healthy
      product-service-redis:
        condition: service_healthy
    env_file:
      - .env
      - ./../../.env #shared env file
    ports:
      - "1003:1003"
    environment:
      PRODUCT_DB_URL: jdbc:postgresql://product-service-db:5432/product-service-db
      KAFKA_LISTENER_AUTO_STARTUP: true

volumes:
  pg_data:
  redis_data:

