services:
  payment-service-db:
    image: postgres:16
    restart: always
    ports:
      - "1114:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: payment-service-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d payment-service-db" ]
      interval: 20s
      timeout: 5s
      retries: 5
    volumes:
      - payment_db_data:/var/lib/postgresql/data

  payment-service:
    build: .
    restart: always
    depends_on:
      payment-service-db:
        condition: service_healthy
    env_file:
      - ./../../.env #shared env file
    ports:
      - "1005:1005"
    environment:
      PAYMENT_SERVICE_PROFILE: dev
      PAYMENT_SERVICE_PORT: 1005
      AUTH_SERVICE_URL: http://auth-service:1001
      DB_USER: admin
      DB_PASSWORD: masterkey
      PAYMENT_GRPC_PORT: 1015
      PAYMENT_DB_URL: jdbc:postgresql://payment-service-db:5432/payment-service-db
      KAFKA_URL: kafka:9092

volumes:
  payment_db_data: