services:
  cart-service-db:
    image: postgres:16
    restart: always
    ports:
      - "${CART_DB_PORT}:5432"
    volumes:
      - /postgres/cart-service/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${CART_DB_NAME}