spring:
  application:
    name: api-gateway
  profiles:
    active: ${API_GATEWAY_PROFILE}

  security:
    oauth2:
      resourceserver:
        jwt:
          authorities-claim-name: roles

server:
  port: ${API_GATEWAY_PORT}




