jwt:
  issuer: ${JWT_ISSUER}
  public-key-url: ${AUTH_SERVICE_URL}/api/v1/public-keys


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug
        security:
          gateway: debug


services:
  auth-url: ${AUTH_SERVICE_URL:http://localhost:8081}
  product-url: ${PRODUCT_SERVICE_URL:http://localhost:8082}
  cart-url: ${CART_SERVICE_URL:http://localhost:8083}
  order-url: ${ORDER_SERVICE_URL:http://localhost:8084}
  payment-url: ${PAYMENT_SERVICE_URL:http://localhost:8085}

