services:
  order-service-db:
    image: postgres:16
    restart: always
    ports:
      - "1113:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: order-service-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d order-service-db" ]
      interval: 20s
      timeout: 5s
      retries: 5
    volumes:
      - order_db_data:/var/lib/postgresql/data

  order-service:
    build: .
    restart: always
    depends_on:
      order-service-db:
        condition: service_healthy
    env_file:
      - ./../../.env #shared env file
    ports:
      - "1004:1004"
    environment:
      ORDER_SERVICE_PORT: 1004
      ORDER_SERVICE_PROFILE: dev
      PRODUCT_GRPC_PORT: 1013
      PAYMENT_GRPC_PORT: 1015
      CART_GRPC_PORT: 1014
      AUTH_SERVICE_URL: http://auth-service:1001
      DB_USER: admin
      DB_PASSWORD: masterkey
      ORDER_DB_URL: jdbc:postgresql://order-service-db:5432/order-service-db
      KAFKA_URL: kafka:9092

volumes:
  order_db_data: