services:
  order-service-db:
    image: postgres:16
    restart: always
    ports:
      - "1113:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: order-service-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d order-service-db" ]
      interval: 20s
      timeout: 5s
      retries: 5
    volumes:
      - order_db_data:/var/lib/postgresql/data

  order-service:
    build: .
    restart: always
    depends_on:
      order-service-db:
        condition: service_healthy
    env_file:
      - ./../../.env #shared env file
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    environment:
      ORDER_DB_URL: jdbc:postgresql://order-service-db:5432/order-service-db
      KAFKA_URL: kafka:9092

volumes:
  order_db_data: