name: Build Cart Service
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v.*.*.*'
    paths:
      - '.github/workflows/build.yml'
      - './.github/workflows/build-cart-service.yml'
      - 'services/cart-service/**'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - './.github/workflows/build-cart-service.yml'
      - 'services/cart-service/**'

permissions:
  contents: read
  packages: write


jobs:
  build:
    name: Build Service
    uses: ./.github/workflows/build.yml
    with:
      context: 'services/cart-service'
      service: 'cart-service'